### ISSUE TITLE
Cannot find packages upon start

### ISSUE THREAD

**Issue by kingofthebongo2008** [loic-sharma/BaGet#302] opened 2019-08-11 06:07 UTC
Hello,
I am using windows. i have updated the code recently and compiled it.
Now when baget boots into my container it cannot find packages.
I get one baget.db which is 65536 bytes with nothing inside, before it was working fine.
I have rebooted because pushing packages showed them in the db, but using then said they are not there.
Here is my config.

ApiKey=NUGET-SERVER-API-KEY
Storage__Type=FileSystem
Storage__Path=c:\var\baget\packages\
Database__Type=Sqlite
Database__ConnectionString=Data Source=c:\var\baget\baget.db
Search__Type=Database
DOTNET_RUNNING_IN_CONTAINER=true
DOTNET_USE_POLLING_FILE_WATCHER=true
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=http://+:80

docker run --mac-address 00:15:5D:2A:1F:2E -it --rm --name nuget-server --network baget --env-file baget.env -v %~dp0baget-data:c:\var\baget baget:latest

In baget-data i have directory with packages.

Seems to me that some paths are incorrect or access to the filesystem is refused.
Thank you

**Comment by alvindizon** [comment] 2019-08-20 07:48
I am also running BaGet on a Docker container, and I transferred my existing Nuget server folder with packages (```Packages```) inside the ```baget-data``` directory, and I can't see the packages upon accessing the web app.

I am running everything on a 64 bit  machine, Ubuntu Server 18.04.

**Comment by kingofthebongo2008** [comment] 2019-08-20 08:51
you must re push them again. this fixes the issue. but there is a  problem
in the recent version

**Comment by loic-sharma** [comment] 2019-09-23 03:28
Hello, this issue was likely caused by me renaming the `Packages` folder to `packages`. This issue shoudl happen to anyone upgrading BaGet on case sensitive file systems. You can lowercase the folder, or like @kingofthebongo2008 suggested, you can reupload all packages. I apologize for the inconvenience, this was an unintended bug. Please let me know if you have any other issues!

**Comment by alvindizon** [comment] 2019-09-30 03:22
I transferred the folders in my old Nuget server directory inside the ```packages``` folder, but upon refreshing the BaGet URL the packages still won't show up. I guess the only way is to reupload via ```dotnet nuget push```.

**Comment by SeppPenner** [comment] 2020-06-11 14:47
This can be closed I would say @loic-sharma.

**Comment by loic-sharma** [comment] 2020-06-12 03:46
Yup, agreed. Please let me know if you need any help

**Closed by loic-sharma** 2020-06-12 03:46 UTC
