### ISSUE TITLE
package removal ui issue

### ISSUE THREAD

**Issue by gowtham4gs** [loic-sharma/BaGet#398] opened 2019-10-22 13:18 UTC
i have removed one version of package from Baget but  UI showing the deleted package name but not showing the next click options of the package ... please do the needful thanks

**Comment by stevenbaylor** [comment] 2019-10-22 15:39
I'm also seeing this. Looks like it could be a serious issue as it seems to have rendered my entire nuget repository unusable.


> nuget delete My.Package 9.9.9 -source baget
> My.Package 9.9.9 will be deleted from the 'https://nuget.sbaylor.com'. Would you like to continue? (y/N) y
> WARNING: Deleting My.Package 9.9.9 from the 'https://nuget.sbaylor.com'.
>   DELETE https://nuget.sbaylor.com/api/v2/package/My.Package/9.9.9
>   NoContent https://nuget.sbaylor.com/api/v2/package/My.Package/9.9.9 732ms
> My.Package 9.9.9 was deleted successfully.
>

In visual studio when I now try to browse the source, in the manage nuget packages screen, it only shows "Error occured" in the window and this is in the package manager output;

> [baget] 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.

Please take a look. My organization has lost access to all nuget packages!!

**Comment by gowtham4gs** [comment] 2019-10-22 18:04
Yes , please give the solution for this..(facing package conflict issue after delete)

**Comment by loic-sharma** [comment] 2019-10-23 15:47
Hi, what are your [`PackageDeletionBehavior`](https://loic-sharma.github.io/BaGet/configuration/#enable-package-hard-deletions) and [`AllowPackageOverwrites`](https://loic-sharma.github.io/BaGet/configuration/#enable-package-overwrites) config values? What are your [database](https://loic-sharma.github.io/BaGet/configuration/#database-configuration) and storage providers?

**Comment by loic-sharma** [comment] 2019-10-23 15:53
I wasn't able to reproduce this. Could you use a tool like [Fiddler](https://www.telerik.com/fiddler) to see the request Visual Studio makes to BaGet that fails?

**Comment by stevenbaylor** [comment] 2019-10-23 15:59
I haven't changed those from the defaults. I'm running the docker container.

baget.env
``` 
ApiKey=myapikey
Storage__Type=FileSystem
Storage__Path=/var/baget/packages
Database__Type=Sqlite
Database__ConnectionString=Data Source=/var/baget/baget.db
Search__Type=Database
```

(from docker inspect)

>             "Env": [
>                 "ApiKey=myapikey",
>                 "Storage__Type=FileSystem",
>                 "Storage__Path=/var/baget/packages",
>                 "Database__Type=Sqlite",
>                 "Database__ConnectionString=Data Source=/var/baget/baget.db",
>                 "Search__Type=Database",
>                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>                 "ASPNETCORE_URLS=http://+:80",
>                 "DOTNET_RUNNING_IN_CONTAINER=true",
>                 "ASPNETCORE_VERSION=2.2.7"
>             ]

**Comment by stevenbaylor** [comment] 2019-10-23 16:58
I think the visual studio problem might be something different. I omitted the "/v3/index.json" from my nuget source. The nuget and dotnet CLIs seem to be OK with that, but it seems visual studio doesn't like it. I think the bug to look for is in the web page. When you soft delete a version of a package, the page for that package doesn't render.

**Comment by loic-sharma** [comment] 2019-10-24 00:43
>  I think the bug to look for is in the web page. When you soft delete a version of a package, the page for that package doesn't render.

I'm unable to reproduce this issue. What version of BaGet are you on? What logs do you see? Can reproduce this using a clean installation? If so, please let me know the full steps.

> I omitted the "/v3/index.json" from my nuget source. 

Please be explicit and include `/v3/index.json`. The client has weird heuristics to try to make this work, but I wouldn't trust that.

**Comment by stevenbaylor** [comment] 2019-10-24 01:56
I was able to reproduce it on both windows and linux. Here's how to reproduce it.

1. Create two versions of a nuget package.

```
 PS C:\baget> dir
 
 
     Directory: C:\baget
 
 
 Mode                LastWriteTime         Length Name
 ----                -------------         ------ ----
 -a----       10/23/2019   9:22 PM           3315 MyAwesomeLib.1.0.0.nupkg
 -a----       10/23/2019   9:22 PM           3314 MyAwesomeLib.1.0.1.nupkg

```

2. Spin up baget in docker.

```
PS C:\baget> docker run -d --name baget `  
   -p 127.0.0.1:80:80  
   -e Storage__Type=FileSystem 
   -e Storage__Path=/var/baget/packages  
   -e Database__Type=Sqlite  
   -e 'Database__ConnectionString=Data Source=/var/baget/baget.db'  
   -e Search__Type=Database  
   -v baget-vol:/var/baget  
 loicsharma/baget:a96c134b8368fbf04b56400faa91aea2892bcf74  
4bff3f2bf0cba3d4295dfd197263412a9cc56add1c02aca8637624e13638a893
```

3. Push both versions of the library

```
PS C:\baget> dotnet nuget push -s http://localhost/v3/index.json .\MyAwesomeLib.1.0.0.nupkg
warn : No API Key was provided and no API Key could be found for 'http://localhost/api/v2/package'. To save an API Key for a source use the 'setApiKey' command.
info : Pushing MyAwesomeLib.1.0.0.nupkg to 'http://localhost/api/v2/package'...
info :   PUT http://localhost/api/v2/package/
info :   Created http://localhost/api/v2/package/ 877ms
info : Your package was pushed.
PS C:\baget>
PS C:\baget> dotnet nuget push -s http://localhost/v3/index.json .\MyAwesomeLib.1.0.1.nupkg
warn : No API Key was provided and no API Key could be found for 'http://localhost/api/v2/package'. To save an API Key for a source use the 'setApiKey' command.
info : Pushing MyAwesomeLib.1.0.1.nupkg to 'http://localhost/api/v2/package'...
info :   PUT http://localhost/api/v2/package/
info :   Created http://localhost/api/v2/package/ 177ms
info : Your package was pushed.
```

4. Browse to http://localhost/packages/MyAwesomeLib
All is well. Should see both versions of the package.

![4](https://user-images.githubusercontent.com/47601715/67446804-c4379580-f5df-11e9-8d1f-4c02b0a23146.png)

5. Delete one of the versions:

```
PS C:\baget> nuget delete MyAwesomeLib 1.0.1 -s http://localhost/v3/index.json
WARNING: No API Key was provided and no API Key could be found for 'http://localhost/api/v2/package'. To save an API Key for a source use the 'setApiKey' command.
MyAwesomeLib 1.0.1 will be deleted from the 'http://localhost/api/v2/package'. Would you like to continue? (y/N) y
WARNING: Deleting MyAwesomeLib 1.0.1 from the 'http://localhost/api/v2/package'.
  DELETE http://localhost/api/v2/package/MyAwesomeLib/1.0.1
  NoContent http://localhost/api/v2/package/MyAwesomeLib/1.0.1 81ms
MyAwesomeLib 1.0.1 was deleted successfully.
```

6. Refresh page at http://localhost/packages/MyAwesomeLib

Only the header is rendered. :(
![6](https://user-images.githubusercontent.com/47601715/67446805-c4379580-f5df-11e9-90f7-16c0ad475f42.png)

**Comment by gowtham4gs** [comment] 2019-10-25 05:50
yes this is the issue please resolve,and how we can access the data base. please help out the problem.

**Comment by gowtham4gs** [comment] 2019-10-30 05:30
Hi Stevenbaylor ,
Please give solution for above issue.

Thanks in advance.

**Comment by gowtham4gs** [comment] 2019-10-30 06:05
please remove header rendering.. :-(

**Comment by stevenbaylor** [comment] 2019-10-30 13:18
@gowtham4gs, I don't have the solution. I'm in the same boat as you.

As a work around you can open the baget.db file in Sqlite and delete rows in the tables that reference the unlisted package.

**Comment by loic-sharma** [comment] 2019-10-31 03:54
Ah the issue is that BaGet doesn't display unlisted packages, but, it displays the latest package regardless of whether it is listed or not. If the latest package happened to be unlisted, the UI would never show anything at all. This is fixed by https://github.com/loic-sharma/BaGet/issues/398

**Comment by loic-sharma** [comment] 2020-02-08 01:37
This should be fixed now. Please let me know if you run into any other issues!

**Closed by loic-sharma** 2020-02-08 01:37 UTC
