### ISSUE TITLE
Baget unable to mirror package (Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.)

### ISSUE THREAD

**Issue by Svisstack** [loic-sharma/BaGet#609] opened 2020-11-17 14:34 UTC
### Describe the bug

Baget is unable to cache a package on Sql Server.

### To Reproduce
1. Using this version of BaGet 3d8a219c5116 (docker image latest)
2. Add official Nuget Mirror
3. Restore package Hangfire.SqlServer 1
4. See error:  Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.

### Expected behavior
Package mirrored.

### Screenshots

```
fail: BaGet.Core.MirrorService[0]
      Failed to mirror package hangfire.sqlserver 1.7.17
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:76c561eb-1dfa-4341-a3d5-0e0debf1093f
Error Number:8152,State:30,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at BaGet.Core.PackageService.AddAsync(Package package, CancellationToken cancellationToken) in /src/BaGet.Core/PackageService.cs:line 28
   at BaGet.Core.PackageIndexingService.IndexAsync(Stream packageStream, CancellationToken cancellationToken) in /src/BaGet.Core/Indexing/PackageIndexingService.cs:line 132
   at BaGet.Core.MirrorService.IndexFromSourceAsync(String id, NuGetVersion version, CancellationToken cancellationToken) in /src/BaGet.Core/Mirror/MirrorService.cs:line 216
```

**Comment by dncnkrs** [comment] 2020-11-18 09:58
I too am having this issue, PR incoming.

**Comment by dncnkrs** [comment] 2020-11-18 10:00
Quick hack btw @Svisstack - you can alter the database column manually to be `nvarchar(max)`, which will fix the issue.

**Comment by Svisstack** [comment] 2020-11-18 11:35
@dncnkrs Thanks. We already added NuGet official repo as a fallback to make this work. I'm hoping however that this will be quickly merged and released.

**Comment by viceice** [comment] 2021-01-26 15:56
Duplicate of #590

**Comment by loic-sharma** [comment] 2021-09-23 04:00
This should be fixed by: https://github.com/loic-sharma/BaGet/releases/tag/v0.4.0-preview2

Please let me know if you have additional feedback or suggestions!

**Closed by loic-sharma** 2021-09-23 04:00 UTC
