### ISSUE TITLE
private feed

### ISSUE THREAD

**Issue by chenzuo** [loic-sharma/BaGet#170] opened 2018-12-10 05:05 UTC
about time?

**Comment by loic-sharma** [comment] 2018-12-11 08:47
This is definitely a feature I want before releasing BaGet 1.0. I'll work on this again once the UI is finalized :)

Closing this as a duplicate of https://github.com/loic-sharma/BaGet/issues/36.

**Closed by loic-sharma** 2018-12-11 08:47 UTC

**Comment by chenzuo** [comment] 2018-12-15 17:30
ths!
