### ISSUE TITLE
SQLite error, no such table Packages

### ISSUE THREAD

**Issue by ibneadam** [loic-sharma/BaGet#76] opened 2018-08-06 04:21 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Built a docker image and tried to run using command :

`docker run -it -p 8090:80 IMAGENAME --name baget`

### What did you expect to see?

BaGet should be running as normal.

### What did you see instead?

The homepage loads okay but a call to search API `/v3/search` throws exceptions about SQLite.

```
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy([p].Id, [p])' could not be translated and will be evaluated locally.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (4ms) [Parameters=[@__p_1='?', @__p_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "t"."Key", "t"."Authors", "t"."Description", "t"."Downloads", "t"."HasReadme", "t"."IconUrl", "t"."Id", "t"."Language", "t"."LicenseUrl", "t"."Listed", "t"."MinClientVersion", "t"."ProjectUrl", "t"."Published", "t"."RequireLicenseAcceptance", "t"."Summary", "t"."Tags", "t"."Title", "t"."Version"
      FROM (
          SELECT "p"."Key", "p"."Authors", "p"."Description", "p"."Downloads", "p"."HasReadme", "p"."IconUrl", "p"."Id", "p"."Language", "p"."LicenseUrl", "p"."Listed", "p"."MinClientVersion", "p"."ProjectUrl", "p"."Published", "p"."RequireLicenseAcceptance", "p"."Summary", "p"."Tags", "p"."Title", "p"."Version"
          FROM "Packages" AS "p"
          ORDER BY "p"."Downloads" DESC
          LIMIT @__p_1 OFFSET @__p_0
      ) AS "t"
      ORDER BY "t"."Id"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Packages'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred in the database while iterating the results of a query for context type 'BaGet.Entities.SqliteContext'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Packages'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
        ......................... more exception code .............................

```

### What is your environment & configuration (arguments, platform, ...)?
Ubuntu 18.04
Docker version 17.12.1-ce, build 7390fc6

**Comment by WernerMairl** [comment] 2018-08-06 05:45
started to work on this.....

**Comment by WernerMairl** [comment] 2018-08-06 07:31
findings on the way:

Controller Tests are not working anymore => we have false positive test results => Health Call for each Controller may supposed

controller tests not working (controller not starting) because web app is composed by multiple assemblies.... 
```            
var assembly = typeof(BaGet.Web.Routes).Assembly;
System.Diagnostics.Debug.Assert(assembly != typeof(Startup).Assembly);
services.AddMvc().AddApplicationPart(assembly);

```

**Comment by WernerMairl** [comment] 2018-08-06 07:41
SearchController is working now, but exception can|t be reproduced with current test )| migrations executed inside TestServer/Builder.....

**Comment by WernerMairl** [comment] 2018-08-06 08:05
We need same spec about migration handling.....
I'm not a EF expert but i found a way that may be working:

a) the .Migrate Methode should work in every case....it creates or updates the database if required or it does nothing.
b) basically there is not other way to check if database exists or not (over different database provider)
currently ".Migrate" is called only in "development" environments

suggest to call .Migrate on EVERY Startup !!

that may slow down some start where nothing is to migrate => we can optimize that later by implementing a --suppress-migration commandline option.....

**Comment by loic-sharma** [comment] 2018-08-06 15:52
Thanks for reporting! I’ll get this fixed ASAP.

@WernerMairl: I’d like to avoid running migrations at every start-up as this is generally a bad idea for production systems. I think a better approach would be getting the docker image to run in development mode.

**Comment by loic-sharma** [comment] 2018-08-07 01:08
@ibneadam What's happening here is that the database is only created automatically if BaGet is running in development mode. To fix this, please follow this guide on how to run BaGet on Docker: https://loic-sharma.github.io/BaGet/#running-baget-on-docker

Alternatively, this command should work: `docker run -it -p 8090:80 IMAGENAME --name baget -e ASPNETCORE_ENVIRONMENT=Development`

Please let me know if this works, or, if you run into any additional issues.

**Comment by loic-sharma** [comment] 2018-09-05 10:09
I'll close this off as BaGet's documentation provides an environment file that automatically runs migrations.

**Closed by loic-sharma** 2018-09-05 10:09 UTC
