### ISSUE TITLE
UI only support show max of 20 packages (Edge and Chrome browsers)

### ISSUE THREAD

**Issue by jcoburn** [loic-sharma/BaGet#475] opened 2020-02-13 14:14 UTC
### Describe the bug
open http://localhost:5000/

expect to see all 133 packages

### To Reproduce
1. Using this version of BaGet v0.3.0-preview2

### Expected behavior
Expected to see all packages that are in BaGet 
C:\Users\jcoburn\Downloads\BaGet3.1.1\packages

### Additional context
Only see 20 using various filters.  also only see 20 when no filter applied.

**Comment by loic-sharma** [comment] 2020-02-14 05:47
Hi, this hasn't implemented yet and is tracked by https://github.com/loic-sharma/BaGet/issues/412. For now, you should be able to see all the results on Visual Studio. I have a fix for the UI here https://github.com/loic-sharma/BaGet/pull/437, please let me know what you think!

I'll close this off as a duplicate of  https://github.com/loic-sharma/BaGet/issues/412

**Closed by loic-sharma** 2020-02-14 05:47 UTC
